### ISSUE TITLE
Can't commit anything

### ISSUE THREAD

**Issue by edwardloveall** [ForkIssues/Tracker#121]
Since the last update, I am unable to commit my staged changes. The commit button does not respond to clicks. Here's a video on a brand new repo with a single, empty file:

![cant-commit](https://user-images.githubusercontent.com/49549/31403812-46842060-adc8-11e7-9dfa-8d9ad0748ca9.gif)

There's not error that is displayed when I do this. Is there any place I can check for errors or try to debug this at all?

**Comment by DanPristupov** [comment]
@edwardloveall please check '~/Library/Caches/Fork/fork.log'. If you can, please send it to support@git-fork.com. You can remove any information which seems to be sensitive for you.

**Comment by edwardloveall** [comment]
Sent!

**Comment by phoolish** [comment]
I am seeing the same problem.

**Comment by DanPristupov** [comment]
@phoolish do you use a hook to modify commit message?

**Comment by phoolish** [comment]
@DanPristupov Nope

**Comment by ametade** [comment]
I'm having the same problem. I'm with Fork version 1.0.61

**Comment by DanPristupov** [comment]
@ametade did it start only recently, or 1.0.61 is the first version which you tried?

**Comment by ametade** [comment]
@DanPristupov I'm not sure but I think it was with this version. I'm also only having problems on a specific repo. On another one everything is fine.

**Comment by DanPristupov** [comment]
@ametade it would be very helpful if you could send the log from '~/Library/Caches/Fork/fork.log' to support@git-fork.com.
I'll be away for a week and can't help you ASAP. Then will spend all my time investigating this problem.

**Comment by ametade** [comment]
Hi @DanPristupov, I already sent it to you by email, Thanks for your help.

**Comment by DanPristupov** [comment]
This bug should be fixed in 1.0.62. Thank you for everybody who helped me to investigate the problem.

**Comment by edwardloveall** [comment]
Hi @DanPristupov! Thanks for all your work on this. Unfortunately, it still doesn't seem to work for me 🙁

![cant-commit](https://user-images.githubusercontent.com/49549/35047353-a8648620-fb67-11e7-9b4f-2b3a5ebbd057.gif)

**Comment by DanPristupov** [comment]
That is bad news :(. I fixed the problem for 3 other people, but it looks like you have a different one.
Can you send the log file one more time please. I added more additional information there.

**Comment by edwardloveall** [comment]
Sent. I'm a developer myself so I get the frustration. Thank you for sticking with it! 😄
