### ISSUE TITLE
Context menu UI isues Big Sur

### ISSUE THREAD

**Issue by palaniraja** [ForkIssues/Tracker#1244]
Drag and Drop context menu UI has minor issues with BigSur

<img width="501" alt="Screen Shot 2021-01-08 at 8 20 31 AM" src="https://user-images.githubusercontent.com/124864/104039238-f86a8800-518a-11eb-899c-5c659b0e21a5.png">

**Comment by DanPristupov** [comment]
We fixed this in Fork 2.3. Please check for updates.

**Comment by palaniraja** [comment]
Unfortunately I still see the issue

![Screen Shot 2021-01-22 at 9 39 39 AM](https://user-images.githubusercontent.com/124864/105525452-f974dc80-5c95-11eb-83d2-7c72a59d22c5.png)
