### ISSUE TITLE
Sporadic "Unable to create 'index.lock': File exists." when switching branches

### ISSUE THREAD

**Issue by Sidelobe** [ForkIssues/Tracker#1303]
I get this error pretty much about 25% of the times I try to switch to a local branch --  then I just repeat the same action and then it works the second time.
```
fatal: Unable to create '/path/to/repo/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
A colleague confirmed to be she experiences the same behaviour on her machine.
We're both using GitFork in macos 10.15 and develop using Xcode.

In contrast to this issue (https://github.com/fork-dev/Tracker/issues/212), I do not have any other git processes running, I'm working purely within GitFork (no CLI git commands in terminal or other git clients open)

Could it be some sort of timing issue? Or could it be Xcode interfering with its source control mechanisms?

**Comment by DanPristupov** [comment]
> Could it be some sort of timing issue?

Yes, most likely. I will try to improve this.

**Comment by coclav-skore** [comment]
Just came here to report that. It worked once I pushed the commits of the current branch to origin, then i could switch branch. Note that i only had this message when trying to switch to master branch, didn't have when i was "navigating" between feature branches

**Comment by Sidelobe** [comment]
Update: I've turned off source control in Xcode for a couple of days now, and the issue persists so it's not (only) related to that.

**Comment by DanPristupov** [comment]
In Fork 2.5 I made an attempt to improve the behavior. Did you notice any difference?

**Comment by Sidelobe** [comment]
Hi Dan
Sorry for the delay, I needed to field-test a bit ;-)
I notice a definitive improvement in the new release - I have not experienced the issue so far.
I'll keep an eye out for during the following weeks, but it's looking good!

Shall we close this (and in the worst case re-open) ?

Thanks for improving this - the icing on the cake on an already awesome tool!

**Comment by DanPristupov** [comment]
@Sidelobe I'm so glad to hear this! ☀️ Thank you very much for the feedback.

**Comment by Sidelobe** [comment]
Oh shoot... it just happened again, this time during a normal local commit :(
I still have the impression it happens less often now, though.

```
$ git commit --file=/var/folders/9j/f6dn759d3sv_x3rv7mkp98bw0000gn/T/53AD0796-CAAA-424A-A70A-9B8DCF5CF904

fatal: Unable to create '/Users/lorenz/Code/XYZ/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Comment by DanPristupov** [comment]
> I still have the impression it happens less often now, though.

This is exactly how it works. It's still possible that repository is blocked for a long time and in that case Fork will show the error message. But before doing that, Fork will check multiple times if the repo is still blocked.
