### ISSUE TITLE
Invalid user name or password when pushing to Bitbucket

### ISSUE THREAD

**Issue by provuejim** [ForkIssues/Tracker#1546]
Today I tried to push to Bitbucket and received this error. I have not changed the password or touched it in any way in months, definitely not since the last push to this remote repository.

<img width="693" alt="Git Error" src="https://user-images.githubusercontent.com/26842788/150610766-8b23c099-67ab-4470-9a3a-82059ab78cc7.png">

I looked in Keychain Access and was surprised to see that this item had been modified only minutes before. I'm not sure but I think 2:08 PM was the time I attempted the push. Would Fork modify this item as it uses it? I wouldn't think that would even be possible.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/26842788/150610943-3fae34cb-e081-4a96-8afb-3ab745c0ae6a.png">

When I do a Get Info on this keychain item and try to show the password, it doesn't show anything. With other items I can show the password, so I think the password on this item may actually be empty. Which of course would explain why it doesn't work. But why would it suddenly change?

Of course the most important question is how to get it working again. Do I need to delete the Bitbucket account from Fork and then set it up again?

I realize that this may have nothing to do with Fork, maybe it is just a Bitbucket problem. But I don't see how Bitbucket could cause a modification of a keychain item on my computer. Thanks in advance for any enlightenment anyone can provide.

**Comment by DanPristupov** [comment]
> Of course the most important question is how to get it working again. Do I need to delete the Bitbucket account from Fork and then set it up again?

Yes, that should fix the problem.

> I have not changed the password or touched it in any way in months, definitely not since the last push to this remote repository.

BitBucket authentication is a bit more complicated. The OAuth token expiration period is just 2 hours and Fork must refresh it all the time.

**Comment by provuejim** [comment]
Thank you. Deleting and re-adding the Bitbucket account was easy, but unfortunately it did not solve the problem.

On a hunch, I tried rebooting the computer. That worked right away. Perhaps some background process was borked. In any case, I'm back in business. 👍
