### ISSUE TITLE
[Feature Request] Workspaces

### ISSUE THREAD

**Issue by gerwim** [ForkIssues/Tracker#1565]
The Windows version has a Workspaces feature. Would be great if this could be ported the Mac version as well.

**Comment by Zandor300** [comment]
Would love to have this as well!

**Comment by RotemCarmon** [comment]
Are there any plans of adding this feature anytime soon?

**Comment by RockyMM** [comment]
This is done

**Comment by DanPristupov** [comment]
@RockyMM it's  not.

**Comment by RockyMM** [comment]
Ahm, sorry, never saw that it's about the Mac. 😅

**Comment by chucker** [comment]
Alternatively, being able to replace the horizontal tabs with a vertical tree would be nice. Like [how Royal TSX does it](https://screenshots.macupdate.com/JPG/45084/45084_1623348552_scr_uc3.jpg).

**Comment by DanPristupov** [comment]
We are working on workspaces. Anyone want to be a beta tester?

**Comment by gerwim** [comment]
Yes! 😀

**Comment by chucker** [comment]
> We are working on workspaces. Anyone want to be a beta tester?

Me! I have way too many tabs in Fork. :-)

**Comment by DanPristupov** [comment]
That was much faster than I expected :).

OK, here is the initial build: https://cdn.fork.dev/prerelease/Fork-2.25.12.dmg
- we reimplemented the window management from scratch, so your open tabs will be reset
- currently there are 2 hard-coded workspaces ('work' and 'home'), later we will allow to modify them
- there are a lot of changes under the hood, so please let me know if something got broken

**Comment by Chris-Hogan-Logikos** [comment]
The workspace switching works well.

The only issue I've seen so far is that the window shifts position,  sometimes drastically, when the workspace is changed.

**Comment by DanPristupov** [comment]
> The only issue I've seen so far is that the window shifts position, sometimes drastically, when the workspace is changed.

The windows in workspace remember their position. But may be we don't really need it. Thank you for bringing attention to that.

**Comment by Chris-Hogan-Logikos** [comment]
> > The only issue I've seen so far is that the window shifts position, sometimes drastically, when the workspace is changed.
> 
> The windows in workspace remember their position. But may be we don't really need it. Thank you for bringing attention to that.

Ah, so they do.  Personally, I'm not a fan of that, but it's not a deal breaker.  Thanks for the explanation.

**Comment by gerwim** [comment]
> > The only issue I've seen so far is that the window shifts position, sometimes drastically, when the workspace is changed.
> 
> The windows in workspace remember their position. But may be we don't really need it. Thank you for bringing attention to that.

I had the exact same thing. I'd rather have it disabled. Other than that -- it works perfect!

**Comment by DanPristupov** [comment]
Yes, I already disabled it

**Comment by DanPristupov** [comment]
Fork 2.26 is out! 🎁
Thank you to everyone who bumped that issue or sent us feedback!

**Comment by sfunke** [comment]
Thanks, awesome to have workspaces on the Mac 🎉

Quick feedback - it seems for now it is not possible to have multiple workspaces open simultaneously:

- open Fork (call it "Window A") -> select workspace A via Toolbar
- open new Window, (call it "Window B") - select workspace B via Toolbar

**Actual behaviour**
Window B closes and Window A gets reloaded with workspace B

**Expected:**
Window A should stay with workspace A, Window B should open Workspace B

**Comment by gerwim** [comment]
> Fork 2.26 is out! 🎁 Thank you to everyone who bumped that issue or sent us feedback!

Awesome! Thank you!

Even though you mentioned you've disabled the window shifting position, I'm still experiencing it (either the top shifts down or the bottom goes up). Note: this a very minor nuisance. Glad to have this feature ;-)

**Comment by infotexture** [comment]
@DanPristupov Congratulations on shipping workspaces in 2.26 on Mac — super useful already! 🙏 

Seems like the only way to access them at the moment is by clicking the toolbar button with the mouse.

Could you add a command to the **View** menu so we can define a custom keyboard shortcut, and expose it via the **Quick Launch** UI, so we can switch workspaces without reaching for the mouse?

**Comment by DanPristupov** [comment]
We just released 2.27 with some workspaces improvements:

- Added workspaces to Quick Launch
- Ability to create nesting using `/` as a separator (same as it works with branches and tags)

**Comment by CodingMarkus** [comment]
> Yes, I already disabled it

Still happening in 2.28.1. Every time I switch workspace, the window jumps to the last position remembered for the other workspace. 

Also if I just switch between two workspaces without moving the window in between, the window always moves a few pixels down and to the right with every switch.

https://github.com/fork-dev/Tracker/assets/26418089/c96e3340-091e-46e0-9617-34faf29eca9a

**Comment by CodingMarkus** [comment]
Also I don't see the point of the workspace feature if it doesn't remember windows positions. 

E.g. I open up 4 windows in the Private workspace and arrange them the way I want them to be arranged. Then I switch to the Work workspace and open 2 windows there and arrange them again. When I now switch back to the Private workspace, I get the same 4 windows as before but all layered on top, making it impossible to work efficiently without first re-arranging the windows again, which somehow makes the feature pointless as a time saver as it would have taken me almost the same time to re-open them without the workspace feature.

**Comment by chucker** [comment]
>Also I don't see the point of the workspace feature if it doesn't remember windows positions.

It's a benefit for me regardless because I inevitably ended up with so many tabs, I could barely read them. This way, I can switch between one "headspace" and another.

But yes, being able to have one window per workspace, with retained position and size, would be even better.

**Comment by CodingMarkus** [comment]
> It's a benefit for me regardless because I inevitably ended up with so many tabs, 
> I could barely read them.

You are aware that you can group tabs in multiple windows, are you? You can also move them between open windows (just use drag'n drop from one window to another one). And you can switch between windows via shortcut (`` CMD+` ``) or using Mission Control or place them on different desktops and switch between the desktops (possibly together with the matching source editors). Also you can have multiple of such tab-grouping windows open at the same time, something you cannot even have with workspaces at all. If this feature is only about remembering tabs (see #1895), it should be named Tab Groups and not Workspaces as just remembering a tab set is not what I'd associate with the term Workspace.
