### ISSUE TITLE
Wrong repository name when use `fork .` cli command

### ISSUE THREAD

**Issue by minimasoftware** [ForkIssues/Tracker#1703]
Opening a fork window using the command line on Mac shows the relative directory passed into the command.

For example, I `cd` into a directory, then called `fork .`, which resulted in the repo name being set to "." in the app.

<img width="1658" alt="Screen Shot 2022-09-20 at 09 29 42" src="https://user-images.githubusercontent.com/63680408/191270735-34ee0df5-1939-4c9d-bd5e-050a2f880a22.png">

Seems to only occur if I call `fork .` in the root directory of the git repo. If I do it in a subdirectory of the repo, it shows the repo name in the fork app.

**Comment by DanPristupov** [comment]
Thank you for reporting the bug.

**Comment by DanPristupov** [comment]
I think this bug is not critical, so I will not force the update for all users.

I released the hotfix here: https://cdn.fork.dev/mac/Fork-2.22.1.dmg. You can download it and install manually.

**Comment by povesteam** [comment]
Hello @DanPristupov,

Thank you for fixing the bug in the tab title. But the dot still appears in the Cmd+P repository opener, even after the update. This includes other cases, for example opening fork on a parent directory `fork ..` or `fork ../..`

Thank you!

**Comment by DanPristupov** [comment]
@povesteam thank you for reporting that!
