### ISSUE TITLE
2.26: toolbar customization "Icon and / or Text" not saved

### ISSUE THREAD

**Issue by gerwim** [ForkIssues/Tracker#1810]
Using 2.26 the configured value for "Icon and Text", "Icon only" and "Text only" are not saved.
Upon restarting Fork or switching workspace, it defaults to "Icon only".

<img width="428" alt="image" src="https://user-images.githubusercontent.com/1841721/218254992-a753a024-4dce-46cc-8971-9d657309765c.png">

**Comment by hjallehallin** [comment]
I can't even get the Customize Toolbar menu to open in version 2.26.1 so I'm stuck with Icon Only.

**Comment by samkusnetz** [comment]
i have the same experience at @gerwim

**Comment by Lenitr** [comment]
Same here, I did notice that any changes made to the actual positioning of buttons etc. is saved, only the setting for the text is not working. So it seems the only thing not working in the toolbar customisation is the Text labels.

**Comment by onevcat** [comment]
Same issue here.

**Comment by KnifeFed** [comment]
After updating to 2.26, the text labels disappeared from the toolbar. After right-clicking the toolbar and re-adding them, everything was fine. Today I updated to macOS Ventura and the text labels are gone again, but nothing happens when I right-click the toolbar. Now I'm stuck with icons only.

**Comment by DanPristupov** [comment]
@KnifeFed https://github.com/fork-dev/Tracker/issues/1735#issuecomment-1296784416

**Comment by Lenitr** [comment]
Didn't seem mention of this in the release notes, but it looks like this is fixed in release 2.27, thanks guys!

**Comment by hjallehallin** [comment]
I still can't access the customize toolbar menu. It seems like the apis used might be deprecated in Ventura? https://developer.apple.com/documentation/appkit/nstoolbar#3993757

**Comment by Lenitr** [comment]
@hjallehallin  Right, I'm still on Montery so I didn't have that issue... I was just seeing that the labels for the buttons were finally working agian. 

But now that you mention it, the "Customize toolbar" option is greyed out now for me too (it wasn't before). Might be related to the comment @DanPristupov mentioned about Ventura not allowing this anymore... perhaps it was disabled entirely for that reason now.

> @KnifeFed [#1735 (comment)](https://github.com/fork-dev/Tracker/issues/1735#issuecomment-1296784416)

**Comment by DanPristupov** [comment]
@Lenitr 

> Ventura not allowing this anymore... perhaps it was disabled entirely for that reason now.

Yes, I confirm that.

**Comment by arturogutierrez** [comment]
> Today I updated to macOS Ventura and the text labels are gone again, but nothing happens when I right-click the toolbar. Now I'm stuck with icons only.

Same here

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1735

**Comment by username0x0a** [comment]
Bump. 2.28 causes the toolbar to only display as `Icon and Text` & there's no possibility to switch it back to `Icon Only`, not even by updating the property list. The possibility to configure the toolbar is greyed out completely which seems strange in the first place. 🤔

@DanPristupov 🙏
