### ISSUE TITLE
Better tab/window management across spaces and reboots.

### ISSUE THREAD

**Issue by memco** [ForkIssues/Tracker#1957]
I would like to see an option in the CLI tool to force `fork` to open the repository in a new window in the current space. Currently my repo is always opened in a specific window on a different space and that window gets moved into the current space. My current workflow is to call `fork` pull the newly opened repo tab out from the other window and then move the other window back to the desired space. Relatedly if I reboot my computer I only ever get one fork window on reboot so I have to pull out several tabs into a new window move those to the desired space and repeat until all the spaces are recreated. Having an option to force the app to open a new window in the current space would allow me to more quickly move to a space and open the desired repos in a window in that specific space.

I do have `Prefer tabs when opening documents` set to `Always` in system settings, which may explain some of my current experience, but I have other apps that are able to support opening a new window in the current space while other windows in other spaces already exist so I hope fork can do it too.

**Comment by HofiOne** [comment]
Even though it is not stated, I'm sure this is a macOS related description.

I do not want to open a new ticket as my issue is included in the description, but I consider it as a bug.

Please fix the current, broken behavior of the tab/window restoration on Fork restart, as it always merges all tabs from all separate windows into a single one on each application restart.

I'm using macOS Sonoma 14.2.1 (23C71), Apple MacBookPro 16-inch, 2021, the issue is constantly happening on this machine, but I guess it is not just OS/Machine related.

**Comment by DanPristupov** [comment]
@HofiOne we fixed that in Fork 2.38

**Comment by HofiOne** [comment]
> @HofiOne we fixed that in Fork 2.38

Working, thank you so much!

**Comment by ssbarnea** [comment]
I am afraid this is still true with 2.49, still does not respect system settings of always using tabs.

**Comment by johntmcintosh** [comment]
> I would like to see an option in the CLI tool to force fork to open the repository in a new window in the current space. Currently my repo is always opened in a specific window on a different space and that window gets moved into the current space. My current workflow is to call fork pull the newly opened repo tab out from the other window and then move the other window back to the desired space.

+1 to this from the original description
