### ISSUE TITLE
Fork CLI always opens new window

### ISSUE THREAD

**Issue by karl-** [ForkIssues/Tracker#2100]
On macOS (Sonoma 14.3), running `fork .` in a repository is always opening a new Fork window, regardless of whether one with the current repository is open already. 

I've tried checking if there are any CLI options with `fork --help` and `fork -h`, but these just open a new window as well.

I'd like `fork $PATH` to open in an existing window, or as a tab if the repository is not already open. Is this possible?

I'm testing using Fork 2.41.1.

**Comment by karl-** [comment]
I found this issue https://github.com/fork-dev/Tracker/issues/1957 that looks like the inverse of what I'm looking for, noting it was fixed in 2.38. So I suppose the question now is whether an option was added somewhere to retain the old behavior?

Also to provide additional information, I have "Prefer tabs when opening documents" set to "Always" on my machine.

**Comment by ssbarnea** [comment]
That is a very annoying bug, still present with 2.49. For example vcode cli has an option for telling it to reuse existing windows. One can define `alias code=code --add` and every time he does `code .`, it will open in the same workspace.

**Comment by DanPristupov** [comment]
@ssbarnea what exactly worries you?

Can you describe steps to reproduce?

I just tried to run `fork .` in a repo and revealed the existing window and tab.

**Comment by karl-** [comment]
@DanPristupov 

https://github.com/user-attachments/assets/a9802cb7-b1ac-4b73-a968-c57ca26c782a

**Comment by karl-** [comment]
@ssbarnea are you using `fish` CLI by chance? I just noticed that this only happens when I'm in my `fish` shell - it does not reproduce with `zsh` or `bash` (fyi @DanPristupov ).

**Comment by karl-** [comment]
Actually it turns it out I simply wasn't calling the Fork CLI tool. I had an old alias that was redirecting my calls to the Fork binary, confusing matters.

`fork -C /path/whatever` works just fine in fish.

Closing this issue as it was an error in my own shell config.
