### ISSUE TITLE
[Feature Request] Allow configuring of file rename threshold

### ISSUE THREAD

**Issue by Stannieman** [ForkIssues/Tracker#2125]
Hello!

By default git diff considers a file as renamed/moved if more than 50% of the contents are the same, otherwise it will show as a removed and a new file. This threshold can be changed by passing the -M parameter.

Assuming Fork uses git diff to visualize changes, would it be possible to make this value configurable?

Reason: Sometimes when refactoring I get situations where tracking changes gets hard due to files not showing as rename. While I might be "doing git wrong", temporarily changing the threshold would help a lot.

**Comment by DanPristupov** [comment]
Making rename threshold configurable is difficult.

> Sometimes when refactoring I get situations where tracking changes gets hard due to files not showing as rename. 

The problem might be caused by bug in Fork when a partial chunk stage changes the file status to from 'renamed' to 'modified'. There is an issue for this: https://github.com/fork-dev/Tracker/issues/1872.

The file will show the correct 'renamed' status after full refresh (Cmd+R or activate some other application and return back to Fork). This can be used as a workaround.

**Comment by Stannieman** [comment]
It's not the bug, it's really the files that have changed enough. In VS Code you can configure this and then it will be detected as move. But it's not like it happens every day and I can use VS Code as workaround, so it's not a big issue.

**Comment by capyvara** [comment]
Hey @DanPristupov , I ran into a issue today that may be related to this, this commit change show as a rename in Fork, but as a delete in Git CLI, GitHub and SourceTree (supposed to be a delete)

<img width="1571" height="174" alt="Image" src="https://github.com/user-attachments/assets/9372d09f-ca05-484f-a639-8a17b7aaf29a" />

Even setting the threshold to 1% in git it still shows properly as a delete:
```
git show 2b871b8ce1a6c8ea5be2e3a4ebddf150d4100cfc -M1% --name-status | grep embedded_basic.bytes.meta 
D	Client/Poe/Assets/Data/Resources/embedded_basic.bytes.meta
```

This is just an example file, it's a 367 changes commit (lower than `diff.renameLimit` default of 400) with a lots of those small files that also got detected as a rename (LFS pointers and small .meta) files changed, but I've tried to change the renameLimit and it always shows as deleted.

I'm not sure how Fork does it, but maybe would be a good idea to rely on the git diff output itself to show those changes, to ensure consistency with other tools, git cli show only 10 renames, while fork shows 100+

At least as a quality of life improvement, one idea may be to allow the Changes tab to be able to search/view the old names too, similar to the Commit tab.

Thanks

**Comment by DanPristupov** [comment]
@capyvara 

> This is just an example file, it's a 367 changes commit (lower than diff.renameLimit default of 400) with a lots of those small files that also got detected as a rename 

this is a bug and it will be fixed in the next update

**Comment by capyvara** [comment]
Hey that was fast, thanks

**Comment by DanPristupov** [comment]
@capyvara actually, I just make a build. I can you confirm that the problem is fixed in https://cdn.fork.dev/prerelease/Fork-2.69.12.dmg?

**Comment by capyvara** [comment]
Seems way better, thanks!

However it still show more renames even than git at 1%
```
git show 2b871b8ce1a6c8ea5be2e3a4ebddf150d4100cfc -M1% --name-status --format= |
  awk -F'\t' '
    { count[substr($1, 1, 1)]++ }
    END {
      print "Renamed:",  count["R"] + 0
      print "Added:",    count["A"] + 0
      print "Modified:", count["M"] + 0
      print "Deleted:",  count["D"] + 0
    }
  '
Renamed: 21
Added: 145
Modified: 23
Deleted: 167
```

While in Fork it seems to show ~80 renames, most of them is those small .metas however, which should be fine for now.

**Comment by DanPristupov** [comment]
@capyvara Can you send to support@fork.dev a deleted/added files pair which are recognized as renamed by Fork and deleted/added by git? Then I can have a look.

**Comment by capyvara** [comment]
Done

**Comment by DanPristupov** [comment]
@capyvara can you try https://cdn.fork.dev/prerelease/Fork-2.69.13.dmg, please?

**Comment by capyvara** [comment]
Hey it seems to me properly matching git's output now, haven't checked all the files as this is a visual manual inspection, but seems fine so far. Thank you.

**Comment by capyvara** [comment]
FYI with this last version, some times I'm having those errors:
```
[Internal bug] different unstaged files count 0 != 6, only in bt: .DS_Store [untracked/untracked], provisioning/.DS_Store [untracked/untracked], scripts/.DS_Store [untracked/untracked], snapser/.DS_Store [untracked/untracked], unity/.DS_Store [untracked/untracked], unity/Packages/.DS_Store [untracked/untracked]
```

fork.log
```
🔷[RepositoryController.swift:581] > fs-mon: invalidateAndRefresh [.repositoryStatus, .repositoryStatus, .changedFiles, .noOptionalLocks]
🔷[RefreshRepositoryCommand.swift:151] > Refresh 'poe-build-tools' status. Updated (1 files)
```
