### ISSUE TITLE
[Feature Request]open specified version file using external editor.

### ISSUE THREAD

**Issue by susan51531** [ForkIssues/Tracker#291]
Is is useful if there a context menu item in diff file list window, that will open the specified version file in external editor.
Just like the **open with** item, this new will open the current version instead of the checked out file;

This is not a wildly used operation.

May be a custom setting is more appropriate. If users can add custom items in context menu or toolbar, just like Alfred app where user can access context information and execute scripts.

**Comment by DanPristupov** [comment]
There's a trick. Right click, "Show in File Tree", Right Click, "Open With" (or simply drag file to the editor).

**Comment by susan51531** [comment]
"Show in File Tree", "Open With" working on the current checked out version.
The file i want open is the version selected in log list not the files in the checked out workspace.
Also i can not drag file in  commit change view to editor, it will do select operation.

**Comment by DanPristupov** [comment]
@susan51531 I just dragged file from file tree and opened **old** version of the file (check the path, an old version will be stored in the temp directory)

**Comment by DanPristupov** [comment]
This behavior seems to be broken in 1.0.69, so I reopen the issue.
- Dragging doesn't work
- `Open With` opens the working directory version, not the selected one.

**Comment by DanPristupov** [comment]
Fixed again.

**Comment by marcomasser** [comment]
Either I’m doing it wrong, or this is still broken in 1.0.70. To be precise: Dragging a file from a revision to the external editor opens the correct file at the correct revision. But right-clicking and selecting either _Open_ or _Open With_ opens the file at the checked-out revision.

**Comment by DanPristupov** [comment]
Yes, you are right. I fixed just first part.
