### ISSUE TITLE
Diff Pane's Horizontal Scrollbar Jumps

### ISSUE THREAD

**Issue by kuthair** [ForkIssues/Tracker#452]
The horizontal scrollbars for the differences pane jumps whenever the window gets activated.

To reproduce:

1. Open Fork, click on Changes at the top of the left nav.
2. Choose a file to see diffs.

-- Notice horizontal scrollbar does NOT start out all the way to the left. --

3. Move the the horizontal scrollbar all the way to the left.
4. Open Safari or any other app to move focus away from Fork.
5. Click back on Fork, watch the horizontal scrollbar in the diffs pane jump to the right.

**Comment by DanPristupov** [comment]
Hi. Confirm this bug. Will fix in the next update.

**Comment by DanPristupov** [comment]
Thank you. The initial scroll position is fixed in 1.0.72.

**Comment by kuthair** [comment]
Awesome, thanks!

**Comment by perry-clarke** [comment]
This still happens for me:
![screen shot 2019-02-25 at 09 17 41](https://user-images.githubusercontent.com/2934889/53355790-b0b41d80-38de-11e9-9997-c9406cad09ae.png)
Note I did not move the horizontal scrollbar to the right, it just ended up scrolled there after a small number of files with long lines were displayed in the diff pane.  It recurs when more files are displayed after the scrollbar is manually reset to the left margin.
Fork 1.0.74.2

**Comment by perry-clarke** [comment]
Should I open a new issue or is commenting here sufficient?

**Comment by DanPristupov** [comment]
Somehow this bug started occurring again. Reopening the issue.

**Comment by DanPristupov** [comment]
I could not fix the bug completely, but in 1.0.76 I significantly improved the behavior.
