### ISSUE TITLE
GitHub notifications not working

### ISSUE THREAD

**Issue by yasuokav** [ForkIssues/Tracker#498]
Version: 1.0.72.2

Login with email:
The status was changed to `Requires authentication` after Fork restart.

Login with username:
The status will remain as `Online`, but can't receive any notifications.

**Comment by Mackarous** [comment]
I have the same issue

**Comment by DanPristupov** [comment]
The log file should contain the details, could you check it? It is located at `~/Library/Caches/Fork/fork.log`

Search the 'notifications' keyword or send the log to my email: support@fork.dev.

**Comment by Mackarous** [comment]
Mine actually finally corrected itself. Restarted Fork, had two instances of the notification menu bar, then disabled it, quit, opened, reenabled and it worked!

**Comment by DanPristupov** [comment]
Actually notifications would just appear automatically once the update time come (in 20 minutes).

I'll have a look how to make the initial user experience less confusing.

**Comment by Mackarous** [comment]
Is it possible to change that update time? 20 mins is quite long for my flow

**Comment by DanPristupov** [comment]
No. But I will decrease it to 15 minutes in the next update.

I'll also check if it's possible to make it configurable without spending much time.

**Comment by Mackarous** [comment]
Hmm. Mine still has problems. It hasn't updated in almost 30 mins. Checking logs...

**Comment by Mackarous** [comment]
```
📢> Fork Version: 1.0.76 Build: 1.0.76 PID: 28991
📢> XCGLogger Version: 4.0.0 - Level: Debug
📢> XCGLogger writing log to: file:///Users/Andrew/Library/Caches/Fork/fork.log
📢[AppDelegate.swift:107] applicationDidFinishLaunching > Git instance: local
📢[RemoteServiceNotificationManager.swift:73] stop() > Stop checking GitHub notifications
📢[RemoteServiceNotificationManager.swift:48] start() > Start checking GitHub notifications
📢[RemoteServiceNotificationManager.swift:95] refresh(force:) > Refresh GitHub notifications...
📢[RemoteServiceNotificationManager.swift:128] notificationsReceived(notifications:newDate:) > Received 1 new GitHub notifications.
```
There is no more indication of `RemoteServiceNotificationManager.swift` after this for 45 minutes

**Comment by DanPristupov** [comment]
The notification list is basically what you see there: https://github.com/notifications. New item may not appear if you already saw it.

**Comment by yasuokav** [comment]
@DanPristupov 
I still have this problem all the time. I waited for 20 minutes, but no luck.
![1](https://user-images.githubusercontent.com/2960293/55861884-4ca99800-5bb2-11e9-9f5c-8f0f8417812a.png)

Login GitHub with username:
```
📢> Fork Version: 1.0.76 Build: 1.0.76 PID: 80963
📢> XCGLogger Version: 4.0.0 - Level: Debug
📢> XCGLogger writing log to: file:///Users/user/Library/Caches/Fork/fork.log
📢[AppDelegate.swift:107] applicationDidFinishLaunching > Git instance: /usr/local/bin/git
📢[RemoteServiceNotificationManager.swift:73] stop() > Stop checking GitHub notifications
📢[RemoteServiceNotificationManager.swift:48] start() > Start checking GitHub notifications
📢[RemoteServiceNotificationManager.swift:95] refresh(force:) > Refresh GitHub notifications...
⚠️[RemoteServiceNotificationManager.swift:107] refresh(force:) > couldNotParseJSON
```

---

Login GitHub with email:
```
📢> Fork Version: 1.0.76 Build: 1.0.76 PID: 81149
📢> XCGLogger Version: 4.0.0 - Level: Debug
📢> XCGLogger writing log to: file:///Users/user/Library/Caches/Fork/fork.log
📢[AppDelegate.swift:107] applicationDidFinishLaunching > Git instance: /usr/local/bin/git
📢[RemoteServiceNotificationManager.swift:73] stop() > Stop checking GitHub notifications
📢[RemoteServiceNotificationManager.swift:48] start() > Start checking GitHub notifications
📢[RemoteServiceNotificationManager.swift:95] refresh(force:) > Refresh GitHub notifications...
📢[GitServiceConnection.swift:52] restoreAuthenticationFromKeychain() > Cannot find keypass entry for 'username' at 'github.com'. Trying to import old session...
⚠️[RemoteServiceNotificationManager.swift:107] refresh(force:) > custom("Requires authentication")
📢[GitServiceConnection.swift:52] restoreAuthenticationFromKeychain() > Cannot find keypass entry for 'username' at 'github.com'. Trying to import old session...
📢[GitServiceConnection.swift:52] restoreAuthenticationFromKeychain() > Cannot find keypass entry for 'username' at 'github.com'. Trying to import old session...
📢[GitServiceConnection.swift:52] restoreAuthenticationFromKeychain() > Cannot find keypass entry for 'username' at 'github.com'. Trying to import old session...
```

**Comment by DanPristupov** [comment]
@yasuokav
```⚠️[RemoteServiceNotificationManager.swift:107] refresh(force:) > couldNotParseJSON```
This is probably the issue.
Not sure how to investigate that... Can I make a build with additional debug logging for you?

**Comment by yasuokav** [comment]
> @yasuokav
> `⚠️[RemoteServiceNotificationManager.swift:107] refresh(force:) > couldNotParseJSON`
> This is probably the issue.
> Not sure how to investigate that... Can I make a build with additional debug logging for you?

Sure.

**Comment by DanPristupov** [comment]
@yasuokav alright, here's the build: https://cdn.fork.dev/prerelease/Fork-gh-notifications.dmg. You don't need to install it, run it right from the DMG file.

This build will log the response from GitHub which Fork fails to parse.
The log might be long, so send it to my email please: support@fork.dev (or support@forkapp.io).

**Comment by yasuokav** [comment]
@DanPristupov 
Notification is disabled in this version without any reason.
There is no icon in the menu bar, and the last line of the log is:
```
📢[RemoteServiceNotificationManager.swift:73] stop() > Stop checking GitHub notifications
```

**Comment by DanPristupov** [comment]
@yasuokav ouch, sorry! I enabled the debug mode (where the notifications are off).
I'm traveling right now and sometimes get distracted.

Here's the updated build: https://cdn.fork.dev/prerelease/Fork-gh-notifications-2.dmg

**Comment by yasuokav** [comment]
@DanPristupov Logs sent to support@fork.dev

**Comment by bsarrazin** [comment]
@DanPristupov would it be possible to add a way to configure the notification refresh frequency as well as setting it to unread only?

**Comment by Mackarous** [comment]
I still seem to have issues with the GH notifications. I don't get anything past the first load

**Comment by DanPristupov** [comment]
@Mackarous Do you use the latest version? I fixed yasuokavs problem in 1.78, bug I forgot to mention that here.

If you do, please send the log file to my email and I'll investigate what's wrong.

**Comment by Mackarous** [comment]
@DanPristupov Sorry for the late response, it seems to be that my notifications are working, but I don't seem to be getting any updates past the first load. The logs show that it is being refreshed properly, but I don't see anything. I have attempted to wait hours before, but no change. When I check GH I end up having 3 or 4 notifications waiting

**Comment by DanPristupov** [comment]
GitHub API just returns same info as on https://github.com/notifications?all=1, but without grouping by repository. Do you see your 'missed' events there?

**Comment by Mackarous** [comment]
Oh wait a minute! I see that I am receiving notifications from the public subscriptions, but the ones that I am struggling with are private repos. I don't get any of those. Could that have something to do with it?

**Comment by DanPristupov** [comment]
Might be. I will investigate that next week and get back to you.

**Comment by DanPristupov** [comment]
OK, it looks like this is a restriction for the non-browser authentication. I will need no switch to web-flow authorization (https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow). This is a major change and I'm not sure how long it will take. So, no ETA unfortunately.

**Comment by Mackarous** [comment]
Ah darn, it's a permissions thing? Thanks for the update tho!

**Comment by DanPristupov** [comment]
Yes. Usually I can simply request the permissions (this is the point of OAuth), but GitHub wants the user to see and confirm the list of private repos it gives access to and then redirect back to my website.

**Comment by Mackarous** [comment]
Ah right. Makes sense

**Comment by DanPristupov** [comment]
@Mackarous I just released Fork 1.0.82 where I switched to web-flow OAuth. Hopefully notifications for private organizations will work now.

I don't have an access to any private organization myself, so I would really appreciate any feedback.

**Comment by Mackarous** [comment]
@DanPristupov updating, and will let you know!

**Comment by Mackarous** [comment]
@DanPristupov I did the following:

1. updated to 1.0.82
2. signed out
3. signed in with new web auth
4. quit
5. relaunched

Still not receiving notifications for private repos, and also noticed that old notifications remain in the panel even if they are read.

**Comment by DanPristupov** [comment]
@Mackarous Thank you.

OK, I just stopped the 1.0.82 update for rest of users and going to try to tweak some parameters. Will be back soon.

**Comment by DanPristupov** [comment]
@Mackarous I made some changes and built Fork 1.0.82.1: https://cdn.fork.dev/mac/Fork-1.0.82.1.dmg. Could you download it and repeat your steps please? You must see differences in the authentication dialog.

**Comment by DanPristupov** [comment]
Here's how the authentication screen looks for me in 1.0.82.1:
<img width="400" alt="Screenshot 2019-07-22 at 23 30 53" src="https://user-images.githubusercontent.com/618115/61666841-c3d5e880-acd8-11e9-9145-9a1e135bfefa.png">

In 1.0.82 it looked like that:
<img width="400" alt="Screenshot 2019-07-22 at 23 29 53" src="https://user-images.githubusercontent.com/618115/61666777-9ee17580-acd8-11e9-90c2-f9683b02db5b.png">

**Comment by Mackarous** [comment]
@DanPristupov updated, waiting on some notifications

**Comment by DanPristupov** [comment]
@Mackarous Fork checks for GitHub notifications every 20 minutes

**Comment by Mackarous** [comment]
@DanPristupov if I quit and restart Fork, I am assuming the notifications will update? If that's the case, I did that while I had notifications for private repos and still haven't seen any in Fork

**Comment by bsrz** [comment]
> Fork checks for GitHub notifications every 20 minutes

that's way too long for a fast pace environment, can that be a setting that the user can change?
