### ISSUE TITLE
Merge commit message stays when resolved via git CLI

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#61]
Steps to reproduce:
1. Pull in a branch to cause a merge conflict
2. View it in Fork's **Changes** view so that Fork adds the "Merge branch 'XXX' of repo-link into YYY" message (with conflict list in the description)
3. Resolve conflicts and commit them via the vanilla `git` CLI
4. The message/description do not go away in Fork, even though the conflict was resolved + committed.

**Comment by olets** [comment]
I'm seeing the same thing when a CLI-run rebase hits an empty commit.

To reproduce:

1. Make a commit
2. `git revert @`
3. `git rebase -i @~2`. In the interactive editor delete the first commit, save, and close
4. Switch to Fork and back to the terminal
5. `git rebase --continue`

**Comment by DanPristupov** [comment]
I forgot to mention that this must be fixed in 1.0.78

**Comment by olets** [comment]
@DanPristupov I'm still seeing a flavor of this in 1.0.78.2. Overlaps a lot with this ticket, but lmk if I should open a new one:

1. In Fork, check "amend"
1. Make a commit with CLI Git
1. In Fork, see that "amend" is still checked (a bug? I'm not sure. if so, it's different from this ticket)
1. Uncheck "amend", see that the message persists

**Comment by DanPristupov** [comment]
@olets 

> In Fork, see that "amend" is still checked (a bug? I'm not sure. if so, it's different from this ticket)

That's correct, the checkbox should stay checked.

> Uncheck "amend", see that the message persists

It should not, until you edited the message. In my case, the message haven't persisted.

**Comment by olets** [comment]
> It should not

I agree, that's what I expect

> In my case, the message haven't persisted.

Interesting, it persists for me. I'll experiment more later.
